void main() {
  try {
    var a = 7;
    var b = 0;
    print(a ~/ b);
  } catch (a) {
    print('Error : $a');
  }
}
